### PR TITLE
PS - Gym Leader Castle Stage Clear

### PR DESCRIPTION
**Pull request by SirEnobMort**
IS SONG - DO NOT DELETE THIS LINE
Game: Pokémon Stadium
Song: Gym Leader Castle Stage Clear
Composers: Kenta Nagata, Hajime Wakai, Toru Minegishi
Converters: SirEnobMort
Category: events

### CODE REVIEW

**Comment by SirEnobMort** [comment]
Audio rebalanced (85% of original volume), original files deleted

**Comment by SirEnobMort** [comment]
Audio rebalanced (77% of original volume), original files deleted

**Comment by wibdiwoh** [comment]
it's still too loud! i suggest you go to the music-discussion channel on discord and take a look at the new pin, it's a full guide on our current points of reference for analyzing volume!

here's a screenshot with the things that i've payed attention to when i looked at your newest iteration:

**Comment by SirEnobMort** [comment]
Sorry for the delay, here's an even softer version, check it out when you have time and let me know if it needs anyting else done.

**Pull request merged**
