### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ZionJaymes**
IS SONG - DO NOT DELETE THIS LINE
Game: Touhou Eiyashou ~ Imperishable Night
Song: Lunatic Eyes ~ Invisible Full Moon
Composers: ZUN
Converters: Zion Jaymes
Category: bgm
Additional Notes: Stoopid Wabbit. Could be a fun choice for any of the songs where you encounter Rabbit.
Tags: Fights, Minigames, Happy

### CODE REVIEW

**Comment by theballaam96** [comment]
You've used a `.m4a` file for your preview. We only accept `.mp3` files, which is why the bot has flagged up that something needs changing with your PR. Please delete the `.m4a` file from your PR and replace it with a `.mp3` instead

**Comment by theballaam96** [comment]
Checks have passed now, thanks for fixing that. We can now go ahead with doing our checks :)

**Comment by theballaam96** [comment]
The MIDI is pretty loud overall and needs rebalancing to be quieter. If you run the MIDI through the play song feature on the converter, it'll show a graph which shows (roughly) how loud it is. Generally it's a good idea not to go above the yellow line, and especially not above the red line.

I'd suggest using the MIDI rebalancer on the converter website and lowering it a fair bit so that these thresholds aren't hit: 
image

**Comment by ZionJaymes** [comment]
yea, I was afraid that might be a slight issue. I can re-balance it no problem.

**Comment by ZionJaymes** [comment]
Replaced the .mid with a quieter version

**Comment by ZionJaymes** [comment]
Thanks for your patience I am TRASH at this git stuff LOL. Literally never used it before this

**Comment by adeleine64DS** [comment]
That one section is still feeling a bit too loud/dense. To me it feels like a panning issue, but perhaps reducing the volume in that section further could also help. Give your tracks room to breathe, if that makes sense.

**Pull request merged**
