### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MorKsQC**
IS SONG - DO NOT DELETE THIS LINE
Game: Donkey Kong Country 3: Dixie Kong's Double Trouble!
Song: Waterfall
Composers: Eveline Fischer
Converters: MorKs
Category: bgm
Tags: Interiors, Calm

### CODE REVIEW

**Comment by Brian0255** [comment]
This sounds good, but it's pretty quiet relative to other submissions we get. Do you think you could raise the volume a bit? I suspect the heavy amount of reverb is the biggest contributing factor here.

**Comment by MorKsQC** [comment]
> This sounds good, but it's pretty quiet relative to other submissions we get. Do you think you could raise the volume a bit? I suspect the heavy amount of reverb is the biggest contributing factor here.

Indeed, I was let known recently that reverb does lower the general volume instead of raising it.
Let me push my changes real quick (couple of minutes)

**Comment by MorKsQC** [comment]
My 3rd push.

This should be better. However, the momentary max seems a bit high for what we actually hear, which is odd.
Here's the data I have:

**Youlean meter:**
image

**Audacity tracks visual:**
image

**Comment by Brian0255** [comment]
Sounds really good now! Judging from my own listening, the peaks seem to be mostly the whistle, which can be rough on the ears if it's not really quiet. The parts with the harp could also be contributing to the peaks being high as it's just generally very loud at lower pitches.

At any rate, the major thing is just the whistle which I've circled on my own audacity graph below if that helps:
image

Happy to accept this if that is adjusted (and sorry for making you resubmit so many times)

**Comment by MorKsQC** [comment]
> Sounds really good now! Judging from my own listening, the peaks seem to be mostly the whistle, which can be rough on the ears if it's not really quiet. The parts with the harp could also be contributing to the peaks being high as it's just generally very loud at lower pitches.
> 
> At any rate, the major thing is just the whistle which I've circled on my own audacity graph below if that helps: image
> 
> Happy to accept this if that is adjusted (and sorry for making you resubmit so many times)

No sweat! That's your job and that only gives me further experience in MIDI rebalancing, so I'm glad to do this. Plus, I wouldn't want to offer subpar material to this community!

Here's my new data, you'll notice that I lowered the whistle volume, so the only "peaking" instruments (at around -11 LUFS) are the Taiko drums, which are low tones and esthetically what the song looks for at that point.

Hopefully, this time, it works out! Hehe

image
image

**Pull request merged**
