### PR TITLE
Price

### PR DESCRIPTION
**Pull request by SchwartzGandhi**
IS SONG - DO NOT DELETE THIS LINE
Game: Persona 5
Song: Price
Category: bgm
Composers: Shoji Meguro
Converters: Schwartz Gandhi
Tags: Interiors

### CODE REVIEW

**Comment by Brian0255** [comment]
So I like how this sounds, but it's unfortunately extremely loud. I went ahead and recorded it in Audacity with Bizhawk's WAV writer and it was peaking at max very frequently, as shown below. I also went ahead and put this into the [loudness tester](https://youlean.co/file-loudness-meter/) and it gave me a max of -5.89 and an average of -9.25. For reference, the max should generally not be higher than -12 and the average should be somewhere around -15 to -17. As it stands, this would need a huge reduction in volume to be approved. If you have any questions, feel free to ask!

image

**Comment by SchwartzGandhi** [comment]
PJ64 3.0.1this is this highest my song gets in my recording
image
both the emulator and the rom are at max volume

**Comment by SchwartzGandhi** [comment]
gotta get to the scrub qual here in a bit so if you want to discuss further, feel free to dm me and I can answer later

**Comment by theballaam96** [comment]
Results from the volume portion of the music converter: 
image

The 153.9 isn't an anomaly either, it was frequently reaching red territory.

**Comment by Brian0255** [comment]
So the thing is, recording via Audacity is inconsistent. I know for sure it changes if you change the emulator's output volume, and probably if you change your desktop audio levels as well. For 100% consistent recordings, you should use Bizhawk DK64 Edition, which you can find instructions for setting up [here](https://github.com/2dos/DK64-Randomizer/wiki/Consoles-and-Emulators#bizhawk-dk64-edition)

Once you have that set up, you'll want to do the following to make recordings (taken from a Ballaam post in Discord):
1) File > AVI/WAV > Config
2) WAV Writer > Ok
3) Set the filename
4) Play the song until it reaches ~4s after it's looped
5) File > AVI/WAV > Stop

This will be completely consistent no matter what you do, such as changing Bizhawk's output volume or speeding up/slowing down the emulator. This is how I test every submission, and this song was relatively much louder than other submissions we get. Hopefully this helps!

**Comment by theballaam96** [comment]
> The 153.9 isn't an anomaly either, it was frequently reaching red territory.

For reference, here's the graph of your song's volume
image

**Pull request merged**
