### PR TITLE
 Landstalker: The Treasures of King Nole - To Great Adventures

### PR DESCRIPTION
**Pull request by SnolidIce**
IS SONG - DO NOT DELETE THIS LINE
Game: Landstalker: The Treasures of King Nole
Song: To Great Adventures
Composers: Motoaki Takenouchi
Converters: Snolid Ice
Category: bgm
Tags: Exteriors, Happy

### CODE REVIEW

**Comment by SnolidIce** [comment]
oh i see thank you, i just took it from the submission form cause i havent submitted like this before , how do i get the duration and time or is there no easy way to get that

**Comment by theballaam96** [comment]
> oh i see thank you, i just took it from the submission form cause i havent submitted like this before , how do i get the duration and time or is there no easy way to get that

Looks all good in terms of the data provided. The message from the `github-actions` bot is just a canary we use to check to see whether everything is good without us having to deep dive.

In terms of the duration & time, the is automatically grabbed from the MIDI file, hence why this is mandatory. The time is also just grabbed from a javascript function.

In general, unless the message from the bot includes:
> Something needs changing: Yes

you don't need to worry about anything unless we say otherwise

**Comment by wibdiwoh** [comment]
mornin

i apologize for the delay in getting to this, we had a few things to sort out!

we at the music-verifying team have spotted a few things that we'd like you to improve:

1 - the bass is panned way too hard to the side, we'd like you to ease a bit on the panning! anywhere between 10% and 30% should work just fine.

2 - the way your version of the song loops isn't ideal... we understand that the original does not have a loop, but since it will loop during dk64 gameplay it is important to find a solution for that! we currently don't have a rule regarding what to do with situations like this, but in your case i suggest removing part of the ending of the song. you can loop to the beginning from the point at 3 mins 22 secs in your mp3 preview.

3 - there's one particular spot in your song that stands out as being too loud, it happens at 0 mins 53 secs in your mp3 preview and i've circled it in the graph below. it is a bass crescendo, and we need you to reduce it's volume by quite a bit.

spot

everything else is great! once these issues are solved, your conversion will be approved

**Comment by SnolidIce** [comment]
ive done loops like that for the past for other songs that dont loop but do u have any suggestions for the looping

**Comment by SnolidIce** [comment]
@wibdiwoh alright i changed the loop, lowered the bass volume and made the pan centered.

idk how i feel about making the volume on the bass lower, i can barley hear it in most parts of the song

**Comment by wibdiwoh** [comment]
oh but you didn't need to lower the bass in the entire song, just in the part i showed in the graph! i took a quick look at the new preview, and that part still sticks out a bit: 

Sem título

it's only 6 notes in total, you could just lower the velocity of those notes instead of lowering the volume of the entire channel!

you can bring the volume for the bass back up if you want, but that specific part needs to be lower so it doesn't spike so much.

**Comment by SnolidIce** [comment]
oh ok i got confused with which part it was, let me fix it really quickly sorry

**Comment by SnolidIce** [comment]
alright i did that, if there is anything else i need to do lmk, if its all good to go if u could close the pr after getting the files/info that would be awesome so i dont have to make a new fork thank you, have a good day :)

**Pull request merged**
